language: node_js

node_js:
  - 12

cache: 
  directories : 
    - "node_modules"
env : 
    - NODE_ENV=development TEST_DB_NAME=energyTest
    
services :
  - mongodb

install:
  - npm install

scripts :
     - cd back-end && npm run test

     
deploy :
  provider: pages
  cleanup : true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master